services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://studentuser:studentpass@db:5432/studentdb

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=studentdb
      - POSTGRES_USER=studentuser
      - POSTGRES_PASSWORD=studentpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  mobile:
    build: ./mobile
    ports:
      - "19000:19000"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    depends_on:
      - backend

volumes:
  postgres_data: